### ISSUE TITLE
[request] Change number of pages

### ISSUE THREAD

**Issue by StevenDTX** [LifeAlgorithm/VitalSourcePrinter#7]
The books that I wish to print actually allows 10 pages per print job.  Is it possible to modify the code to print 10 pages at a time?

Thanks.

**Comment by LifeAlgorithm** [comment]
Yes, this is doable. Does the regular script with 2 pages work for you? I ask because a few users have run into issues with the tab, and I want to make sure that at a baseline, the normal script works before I proceed making a new script to adjust for different pages.

**Comment by StevenDTX** [comment]
Yes, the 2 page at a time script works great. Thank you for your efforts!

**Comment by LifeAlgorithm** [comment]
You're welcome. I wrote a new script. I got it to compile, but I don't have a book that allows 10 pages, so I'm not sure if it works. It's on a test branch:

https://github.com/LifeAlgorithm/VitalSourcePrinter/blob/TabFix/VitalSourcePrinter.py

**Comment by StevenDTX** [comment]
It works great!  Thank you very much.  

Note: The first print still only prints 2 pages, but the next print does however many you tell it.

**Comment by LifeAlgorithm** [comment]
I did that for speed reasons, but I can see how it might be unclear to someone who uses the script. I'll look into changing that later, but I'm glad the script is functional for now.
